name: CI

on: 
  create:
    branches: 
      - dev
  push:
    branches:
    - dev
    tags:
    - 'v*.*.*'

    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'Model/Model.csproj'
      OWNER_REPOSITORY: LucianoSponton

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Set env
      run: echo "VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
    - name: Test
      run: |
          echo $VERSION
          echo ${{ env.VERSION }}
          
          
    #- name: Set VERSION variable from tag
     # run: echo "VERSION=1.0.0" >> $GITHUB_ENV
      

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $PROJECT

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: | 
        dotnet build Model/Model.csproj --configuration Release /p:Version=${VERSION}  --no-restore
        
    - name: Auth
      run: dotnet nuget add source --username LucianoSponton --password ${{ secrets.TOKEN_GITHUB }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/LucianoSponton/index.json"
    
    - name: Pack
      run: dotnet pack Model/Model.csproj --configuration Release
      
    - name: Publish
      run:  dotnet nuget push $GITHUB_WORKSPACE/Model/bin/Release/*.nupkg  --api-key ${{ secrets.TOKEN_GITHUB }} --source "https://nuget.pkg.github.com/LucianoSponton/index.json"

    #- name: publish nuget package
    #  uses: myci-actions/publish-nuget@5
    #  with:
   #     filename: '*.nupkg'
   #     api-key: ${{ secrets.TOKEN_GITHUB }}
   #     repo-url: 'https://nuget.pkg.github.com/${{env.OWNER_REPOSITORY}}/index.json'

