name: CI

on: 
  create:
    branches: 
      - dev
  push:
    branches:
    - dev
    tags:
    - 'v*.*.*'

    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'Model/Model.csproj'
      OWNER_REPOSITORY: LucianoSponton

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Checkout code
      uses: actions/checkout@master

    - name: Extract version
      id: extract_version
      uses: Saionaro/extract-package-version@v1.0.6
      # From now you can access the version
    - name: Print version
      run: echo ${{ steps.extract_version.outputs.version }}
    
    - name: Set env
      run: echo "VERSION=1.0.2" >> $GITHUB_ENV
    - name: Test
      run: |
          echo $VERSION
          echo ${{ env.VERSION }}
          
          
    #- name: Set VERSION variable from tag
     # run: echo "VERSION=1.0.0" >> $GITHUB_ENV
      

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $PROJECT

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    # Compilo el proyecto y establesco version de la dll
    - name: Build
      run: | 
        dotnet build Model/Model.csproj --configuration Release /p:Version=${VERSION}  --no-restore
        
   # Me autentico en mi repositorio nuget
    - name: Auth
      run: dotnet nuget add source --username LucianoSponton --password ${{ secrets.TOKEN_GITHUB }} --store-password-in-clear-text --name github "https://nuget.pkg.github.com/LucianoSponton/index.json"
  
  # Genero el paquete en modo Release
    - name: Pack
      run: dotnet pack Model/Model.csproj --configuration Release
      
  # Publico la ultima version generada del paquete en mi repositorio nuget
    - name: Publish
      run:  dotnet nuget push $GITHUB_WORKSPACE/Model/bin/Release/*${VERSION}.nupkg  --api-key ${{ secrets.TOKEN_GITHUB }} --source "https://nuget.pkg.github.com/LucianoSponton/index.json"



