name: Create Release

on: push

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout branch
      ##  uses: actions/checkout@v2
        
      - uses: actions/checkout@v3
      - uses: rickstaa/action-create-tag@v1
        id: generate_tag
        with:
          tag: "latest"
          message: "Latest release"

      #- name: Generate release tag
      ##  uses: amitsingh-007/next-release-tag@v2.2.0
      #  id: generate_tag
      #  with:
      #    github_token: ${{ secrets.TOKEN_GITHUB }} 

      ###### se muestra solamente el Tag creado ###### 
      - name: Show Next Tag
        run: echo "VERSION=${{ steps.generate_tag.outputs.release_tag }}"  >> $GITHUB_ENV
        
     # - name: Create Release
     #   uses: actions/create-release@v1
     #   env:
     #     GITHUB_TOKEN: ${{ secrets.TOKEN_GITHUB }}
    #    with:
    #      tag_name: ${{ env.release_tag }}
    #      release_name: Release ${{ env.release_tag }}
