name: CI

on:
  create:
    branches: 
      - dev
  push:
    branches:
    - dev

    
jobs:
  build:

    env:
      BUILD_CONFIG: 'Release'
      PROJECT: 'Model/Model.csproj'
      OWNER_REPOSITORY: LucianoSponton

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    

    - name: Set VERSION variable from tag
      run: echo "VERSION=1.0.0" >> $GITHUB_ENV
    

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v1.0.5

    - name: Restore dependencies
      run: nuget restore $PROJECT

    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.x

    - name: Build
      run: | 
        dotnet build Model/Model.csproj --configuration Release /p:Version=${VERSION}  --no-restore
      
    - name: Push
      run: dotnet nuget push $GITHUB_WORKSPACE/Model/bin/Release/*.nupkg --source https://nuget.pkg.github.com/${{env.OWNER_REPOSITORY}}/index.json --api-key ${GITHUB_TOKEN}
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
